In [2]:
import pandas as pd
import numpy as np

# Reading and inspection

In [ ]:
#import and read
#import and read the datbase store in a variable caleed movies

In [3]:
movies=pd.read_excel("C:\\Users\\Win\Desktop\\IMDB_Movies.xlsx")
orgdata=movies
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,165.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

# Inspect The dataframe

In [4]:
movies.shape

(5043, 28)

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5023 non-null   object
 19  language                   5031 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(12), int64(3), object(13)
memory usage: 1.1+ MB

In [6]:
movies.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          20
language                      12
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

# Cleaning the data

In [7]:
movies

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,165.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [8]:
movies.isnull().sum(axis=0).sort_values(ascending=False)

gross                        884
budget                       492
aspect_ratio                 329
content_rating               303
plot_keywords                153
title_year                   108
director_name                104
director_facebook_likes      104
num_critic_for_reviews        50
actor_3_name                  23
actor_3_facebook_likes        23
num_user_for_reviews          20
color                         19
duration                      15
facenumber_in_poster          13
actor_2_name                  13
actor_2_facebook_likes        13
language                      12
actor_1_name                   7
actor_1_facebook_likes         7
country                        5
cast_total_facebook_likes      0
num_voted_users                0
movie_title                    0
movie_imdb_link                0
genres                         0
imdb_score                     0
movie_facebook_likes           0
dtype: int64

In [9]:
movies.isnull().sum(axis=1).sort_values(ascending=False)

279     15
4       13
4945    11
2241    11
2342    10
        ..
1703     0
1702     0
1701     0
1700     0
5042     0
Length: 5043, dtype: int64

In [10]:
movies.isnull().sum(axis=0).sort_values(ascending=False)/len(movies)*100

gross                        17.529248
budget                        9.756098
aspect_ratio                  6.523895
content_rating                6.008328
plot_keywords                 3.033908
title_year                    2.141582
director_name                 2.062265
director_facebook_likes       2.062265
num_critic_for_reviews        0.991473
actor_3_name                  0.456078
actor_3_facebook_likes        0.456078
num_user_for_reviews          0.396589
color                         0.376760
duration                      0.297442
facenumber_in_poster          0.257783
actor_2_name                  0.257783
actor_2_facebook_likes        0.257783
language                      0.237954
actor_1_name                  0.138806
actor_1_facebook_likes        0.138806
country                       0.099147
cast_total_facebook_likes     0.000000
num_voted_users               0.000000
movie_title                   0.000000
movie_imdb_link               0.000000
genres                        0.000000
imdb_score                    0.000000
movie_facebook_likes          0.000000
dtype: float64

# Drop unnecessary column

#Some columns are not required thats why i'm removing some columns i want movies with respect to ratings, gross collection,popularity of movies

In [11]:
movies.drop(["color","duration","director_facebook_likes","actor_3_facebook_likes","actor_2_name","actor_1_facebook_likes","country","content_rating","actor_2_facebook_likes"],axis=1,inplace=True)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,AvatarÂ,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,237000000.0,2009.0,7.9,1.78,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's EndÂ,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,300000000.0,2007.0,7.1,2.35,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,SpectreÂ,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,245000000.0,2015.0,6.8,2.35,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight RisesÂ,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701,English,250000000.0,2012.0,8.5,2.35,164000
4,Doug Walker,NaN,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force AwakensÂ ...,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,,NaN,NaN,NaN,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Scott Smith,1.0,NaN,Comedy|Drama,Eric Mabius,Signed Sealed DeliveredÂ,629,2283,Crystal Lowe,2.0,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,6,English,NaN,2013.0,7.7,NaN,84
5039,NaN,43.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,The FollowingÂ,73839,1753,Sam Underwood,1.0,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,359,English,NaN,NaN,7.5,16.00,32000
5040,Benjamin Roberds,13.0,NaN,Drama|Horror|Thriller,Eva Boehnke,A Plague So PleasantÂ,38,0,David Chandler,0.0,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,3,English,1400.0,2013.0,6.3,NaN,16
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai CallingÂ,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9,English,NaN,2012.0,6.3,2.35,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with DrewÂ,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84,English,1100.0,2004.0,6.6,1.85,456

In [12]:
round(movies.isnull().sum().sort_values(ascending=False)/len(movies)*100,2)

gross                        17.53
budget                        9.76
aspect_ratio                  6.52
plot_keywords                 3.03
title_year                    2.14
director_name                 2.06
num_critic_for_reviews        0.99
actor_3_name                  0.46
num_user_for_reviews          0.40
facenumber_in_poster          0.26
language                      0.24
actor_1_name                  0.14
cast_total_facebook_likes     0.00
movie_imdb_link               0.00
num_voted_users               0.00
movie_title                   0.00
imdb_score                    0.00
genres                        0.00
movie_facebook_likes          0.00
dtype: float64

# Drop unnecessary column with high  null percentages

In [13]:
movies[movies["gross"].notnull()]

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,AvatarÂ,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,237000000.0,2009.0,7.9,1.78,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's EndÂ,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,300000000.0,2007.0,7.1,2.35,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,SpectreÂ,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,245000000.0,2015.0,6.8,2.35,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight RisesÂ,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701,English,250000000.0,2012.0,8.5,2.35,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John CarterÂ,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738,English,263700000.0,2012.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,CaviteÂ,589,0,Quynn Ton,0.0,jihad|mindanao|philippines|security guard|squa...,http://www.imdb.com/title/tt0428303/?ref_=fn_t...,35,English,7000.0,2005.0,6.3,NaN,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El MariachiÂ,52055,147,Consuelo GÃ³mez,0.0,assassin|death|guitar|gun|mariachi,http://www.imdb.com/title/tt0104815/?ref_=fn_t...,130,Spanish,7000.0,1992.0,6.9,1.37,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry BishÃ©,NewlywedsÂ,1338,690,Daniella Pineda,1.0,written and directed by cast member,http://www.imdb.com/title/tt1880418/?ref_=fn_t...,14,English,9000.0,2011.0,6.4,NaN,413
5041,Daniel Hsia,14.0,10443.0,Comedy|Drama|Romance,Alan Ruck,Shanghai CallingÂ,1255,2386,Eliza Coupe,5.0,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,9,English,NaN,2012.0,6.3,2.35,660
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with DrewÂ,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84,English,1100.0,2004.0,6.6,1.85,456

In [14]:
#movies=pd.set_option()

In [15]:
round(movies.isnull().sum(axis=1).sort_values(ascending=False) > 5).sum()

15.0

In [16]:
[movies.isnull().sum(axis=1).sort_values(ascending=False) <= 5]

[279     False
 2342    False
 4       False
 2870    False
 2241    False
         ...
 1703     True
 1702     True
 1701     True
 1700     True
 5042     True
 Length: 5043, dtype: bool]

In [17]:
movies= movies[movies["gross"].notnull()]
movies= movies[movies["budget"].notnull()]

In [18]:
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes
0,James Cameron,723.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,AvatarÂ,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,237000000.0,2009.0,7.9,1.78,33000
1,Gore Verbinski,302.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's EndÂ,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,300000000.0,2007.0,7.1,2.35,0
2,Sam Mendes,602.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,SpectreÂ,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,245000000.0,2015.0,6.8,2.35,85000
3,Christopher Nolan,813.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight RisesÂ,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701,English,250000000.0,2012.0,8.5,2.35,164000
5,Andrew Stanton,462.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John CarterÂ,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738,English,263700000.0,2012.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,424760.0,Drama|Sci-Fi|Thriller,Shane Carruth,PrimerÂ,72639,368,Casey Gooden,0.0,changing the future|independent film|invention...,http://www.imdb.com/title/tt0390384/?ref_=fn_t...,371,English,7000.0,2004.0,7.0,1.85,19000
5034,Neill Dela Llana,35.0,70071.0,Thriller,Ian Gamazon,CaviteÂ,589,0,Quynn Ton,0.0,jihad|mindanao|philippines|security guard|squa...,http://www.imdb.com/title/tt0428303/?ref_=fn_t...,35,English,7000.0,2005.0,6.3,NaN,74
5035,Robert Rodriguez,56.0,2040920.0,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El MariachiÂ,52055,147,Consuelo GÃ³mez,0.0,assassin|death|guitar|gun|mariachi,http://www.imdb.com/title/tt0104815/?ref_=fn_t...,130,Spanish,7000.0,1992.0,6.9,1.37,0
5037,Edward Burns,14.0,4584.0,Comedy|Drama,Kerry BishÃ©,NewlywedsÂ,1338,690,Daniella Pineda,1.0,written and directed by cast member,http://www.imdb.com/title/tt1880418/?ref_=fn_t...,14,English,9000.0,2011.0,6.4,NaN,413
5042,Jon Gunn,43.0,85222.0,Documentary,John August,My Date with DrewÂ,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84,English,1100.0,2004.0,6.6,1.85,456

# SUBSTACK 2.5: Fill NaN Values

In [19]:
# you might notice that language column has some NAN values Here on inspection you will see that it is safe to replace all the missing values with 'English'

In [20]:
movies.groupby('language').language.count().sort_values(ascending=False)

language
English       3707
French          37
Spanish         26
Mandarin        15
German          13
Japanese        12
Hindi           10
Cantonese        8
Italian          7
Portuguese       5
Korean           5
Norwegian        4
Dutch            3
Persian          3
Danish           3
Hebrew           3
Thai             3
Indonesian       2
Aboriginal       2
Dari             2
Czech            1
Vietnamese       1
Aramaic          1
Telugu           1
Swedish          1
Bosnian          1
Russian          1
Romanian         1
Arabic           1
Icelandic        1
Dzongkha         1
None             1
Mongolian        1
Maya             1
Filipino         1
Hungarian        1
Kazakh           1
Zulu             1
Name: language, dtype: int64

In [21]:
movies.language.describe()

count        3888
unique         38
top       English
freq         3707
Name: language, dtype: object

In [22]:
movies.language = movies.language.fillna('English')

In [23]:
movies.groupby('language').language.count().sort_values(ascending=False)

language
English       3710
French          37
Spanish         26
Mandarin        15
German          13
Japanese        12
Hindi           10
Cantonese        8
Italian          7
Portuguese       5
Korean           5
Norwegian        4
Dutch            3
Persian          3
Danish           3
Hebrew           3
Thai             3
Indonesian       2
Aboriginal       2
Dari             2
Czech            1
Vietnamese       1
Aramaic          1
Telugu           1
Swedish          1
Bosnian          1
Russian          1
Romanian         1
Arabic           1
Icelandic        1
Dzongkha         1
None             1
Mongolian        1
Maya             1
Filipino         1
Hungarian        1
Kazakh           1
Zulu             1
Name: language, dtype: int64

In [24]:
round(movies.isnull().sum().sort_values(ascending=False)/len(movies)*100,2)

aspect_ratio                 1.93
plot_keywords                0.80
actor_3_name                 0.26
facenumber_in_poster         0.15
actor_1_name                 0.08
num_critic_for_reviews       0.03
num_user_for_reviews         0.00
imdb_score                   0.00
title_year                   0.00
budget                       0.00
language                     0.00
director_name                0.00
movie_imdb_link              0.00
cast_total_facebook_likes    0.00
num_voted_users              0.00
movie_title                  0.00
genres                       0.00
gross                        0.00
movie_facebook_likes         0.00
dtype: float64

# Substack 2.6: Check the number of retained rows

In [25]:
# you might know that the two columns viz.num_critic_for_reviews and actor_1_name have small percentage of NaN valuesleft. you can let these columns as it is for now.check the number and percentage of the retained rows retained after completing the task above

In [26]:
len(movies)

3891

In [27]:
len(movies)/len(orgdata)*100

77.15645449137418

In [28]:
#checkpoint 1: You might have noticed that we still have around 77% of the rows

# TASK 3: Data analysis

In [29]:
#Subtask 3.1: Change the unit of columns 
#convert the unit of the budget and gross columns from $ to million

In [30]:
movies['budget']=movies['budget']/1000000
movies['gross']=movies['gross']/1000000

In [31]:
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,AvatarÂ,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,237.0000,2009.0,7.9,1.78,33000
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's EndÂ,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,300.0000,2007.0,7.1,2.35,0
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,SpectreÂ,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,245.0000,2015.0,6.8,2.35,85000
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight RisesÂ,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701,English,250.0000,2012.0,8.5,2.35,164000
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John CarterÂ,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738,English,263.7000,2012.0,6.6,2.35,24000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,PrimerÂ,72639,368,Casey Gooden,0.0,changing the future|independent film|invention...,http://www.imdb.com/title/tt0390384/?ref_=fn_t...,371,English,0.0070,2004.0,7.0,1.85,19000
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,CaviteÂ,589,0,Quynn Ton,0.0,jihad|mindanao|philippines|security guard|squa...,http://www.imdb.com/title/tt0428303/?ref_=fn_t...,35,English,0.0070,2005.0,6.3,NaN,74
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El MariachiÂ,52055,147,Consuelo GÃ³mez,0.0,assassin|death|guitar|gun|mariachi,http://www.imdb.com/title/tt0104815/?ref_=fn_t...,130,Spanish,0.0070,1992.0,6.9,1.37,0
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry BishÃ©,NewlywedsÂ,1338,690,Daniella Pineda,1.0,written and directed by cast member,http://www.imdb.com/title/tt1880418/?ref_=fn_t...,14,English,0.0090,2011.0,6.4,NaN,413
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with DrewÂ,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84,English,0.0011,2004.0,6.6,1.85,456

In [32]:
# Find the movies with highest profit 
# 1 create a new column called profit which contains the difference of the two columns gross and budget.
#extract the top ten profiting movies in descending order and store them in a new dataframe .top 10

In [33]:
movies['profit']= movies['gross'] - movies['budget']
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,AvatarÂ,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,237.0000,2009.0,7.9,1.78,33000,523.505847
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's EndÂ,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,300.0000,2007.0,7.1,2.35,0,9.404152
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,SpectreÂ,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,245.0000,2015.0,6.8,2.35,85000,-44.925825
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight RisesÂ,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701,English,250.0000,2012.0,8.5,2.35,164000,198.130642
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John CarterÂ,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738,English,263.7000,2012.0,6.6,2.35,24000,-190.641321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,PrimerÂ,72639,368,Casey Gooden,0.0,changing the future|independent film|invention...,http://www.imdb.com/title/tt0390384/?ref_=fn_t...,371,English,0.0070,2004.0,7.0,1.85,19000,0.417760
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,CaviteÂ,589,0,Quynn Ton,0.0,jihad|mindanao|philippines|security guard|squa...,http://www.imdb.com/title/tt0428303/?ref_=fn_t...,35,English,0.0070,2005.0,6.3,NaN,74,0.063071
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El MariachiÂ,52055,147,Consuelo GÃ³mez,0.0,assassin|death|guitar|gun|mariachi,http://www.imdb.com/title/tt0104815/?ref_=fn_t...,130,Spanish,0.0070,1992.0,6.9,1.37,0,2.033920
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry BishÃ©,NewlywedsÂ,1338,690,Daniella Pineda,1.0,written and directed by cast member,http://www.imdb.com/title/tt1880418/?ref_=fn_t...,14,English,0.0090,2011.0,6.4,NaN,413,-0.004416
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with DrewÂ,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84,English,0.0011,2004.0,6.6,1.85,456,0.084122

In [34]:
top10 =movies.sort_values(by='profit',ascending=False).head(10)
top10

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,AvatarÂ,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,237.0,2009.0,7.9,1.78,33000,523.505847
29,Colin Trevorrow,644.0,652.177271,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,Jurassic WorldÂ,418214,8458,Omar Sy,0.0,dinosaur|disaster film|experiment gone wrong|j...,http://www.imdb.com/title/tt0369610/?ref_=fn_t...,1290,English,150.0,2015.0,7.0,2.00,150000,502.177271
26,James Cameron,315.0,658.672302,Drama|Romance,Leonardo DiCaprio,TitanicÂ,793059,45223,Gloria Stuart,0.0,artist|love|ship|titanic|wet,http://www.imdb.com/title/tt0120338/?ref_=fn_t...,2528,English,200.0,1997.0,7.7,2.35,26000,458.672302
3024,George Lucas,282.0,460.935665,Action|Adventure|Fantasy|Sci-Fi,Harrison Ford,Star Wars: Episode IV - A New HopeÂ,911097,13485,Kenny Baker,1.0,death star|empire|galactic war|princess|rebellion,http://www.imdb.com/title/tt0076759/?ref_=fn_t...,1470,English,11.0,1977.0,8.7,2.35,33000,449.935665
3080,Steven Spielberg,215.0,434.949459,Family|Sci-Fi,Henry Thomas,E.T. the Extra-TerrestrialÂ,281842,2811,Peter Coyote,0.0,bicyclist|boy|doll|star wars reference|voice i...,http://www.imdb.com/title/tt0083866/?ref_=fn_t...,515,English,10.5,1982.0,7.9,1.85,34000,424.449459
794,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The AvengersÂ,995415,87697,Scarlett Johansson,3.0,alien invasion|assassin|battle|iron man|soldier,http://www.imdb.com/title/tt0848228/?ref_=fn_t...,1722,English,220.0,2012.0,8.1,1.85,123000,403.279547
17,Joss Whedon,703.0,623.279547,Action|Adventure|Sci-Fi,Chris Hemsworth,The AvengersÂ,995415,87697,Scarlett Johansson,3.0,alien invasion|assassin|battle|iron man|soldier,http://www.imdb.com/title/tt0848228/?ref_=fn_t...,1722,English,220.0,2012.0,8.1,1.85,123000,403.279547
509,Roger Allers,186.0,422.783777,Adventure|Animation|Drama|Family|Musical,Matthew Broderick,The Lion KingÂ,644348,6458,Niketa Calame,0.0,king|prince|scar|uncle|unnecessary guilt,http://www.imdb.com/title/tt0110357/?ref_=fn_t...,656,English,45.0,1994.0,8.5,1.66,17000,377.783777
240,George Lucas,320.0,474.544677,Action|Adventure|Fantasy|Sci-Fi,Natalie Portman,Star Wars: Episode I - The Phantom MenaceÂ,534658,37723,Ian McDiarmid,1.0,alien|character says i have a bad feeling abou...,http://www.imdb.com/title/tt0120915/?ref_=fn_t...,3597,English,115.0,1999.0,6.5,2.35,13000,359.544677
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark KnightÂ,1676169,57802,Morgan Freeman,0.0,based on comic book|dc comics|psychopath|star ...,http://www.imdb.com/title/tt0468569/?ref_=fn_t...,4667,English,185.0,2008.0,9.0,2.35,37000,348.316061

# Drop duplicate value

In [35]:
#after finding the top 10 profiting movies.i might have notice the duplicate valuesso, it seems like the datafarme has duplicate values as wll.Drop the duplicate value from the dataframe and repeat subtask 3.2.

In [36]:
movies.drop_duplicates(keep='first',inplace=True)

In [37]:
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,profit
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,AvatarÂ,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054,English,237.0000,2009.0,7.9,1.78,33000,523.505847
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's EndÂ,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238,English,300.0000,2007.0,7.1,2.35,0,9.404152
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,SpectreÂ,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994,English,245.0000,2015.0,6.8,2.35,85000,-44.925825
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight RisesÂ,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701,English,250.0000,2012.0,8.5,2.35,164000,198.130642
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John CarterÂ,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738,English,263.7000,2012.0,6.6,2.35,24000,-190.641321
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,PrimerÂ,72639,368,Casey Gooden,0.0,changing the future|independent film|invention...,http://www.imdb.com/title/tt0390384/?ref_=fn_t...,371,English,0.0070,2004.0,7.0,1.85,19000,0.417760
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,CaviteÂ,589,0,Quynn Ton,0.0,jihad|mindanao|philippines|security guard|squa...,http://www.imdb.com/title/tt0428303/?ref_=fn_t...,35,English,0.0070,2005.0,6.3,NaN,74,0.063071
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El MariachiÂ,52055,147,Consuelo GÃ³mez,0.0,assassin|death|guitar|gun|mariachi,http://www.imdb.com/title/tt0104815/?ref_=fn_t...,130,Spanish,0.0070,1992.0,6.9,1.37,0,2.033920
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry BishÃ©,NewlywedsÂ,1338,690,Daniella Pineda,1.0,written and directed by cast member,http://www.imdb.com/title/tt1880418/?ref_=fn_t...,14,English,0.0090,2011.0,6.4,NaN,413,-0.004416
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with DrewÂ,4285,163,Jon Gunn,0.0,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,84,English,0.0011,2004.0,6.6,1.85,456,0.084122

In [38]:
#checkpoint: i might spot two movies directed by james Cameron in the list

# Find imdb Top 250
1.create a new dataframe imdb_top_250 and store the top 250 movies with the highest ImDB Rating (corresponding to the column imdb_score) Also make sure that for all of these movies. the num_voted_user to greater than 25,000 Also add a rank column containing the values 1 to 250 indicating the ranks of the corresponding films.
2.Extract the movies in the IMDb_Top_250 dataframe which are not in the english language and store them in a new dataframe named Top_Forigen_lang_film

In [39]:
imdb_Top_250=movies[movies['num_voted_users'] > 25000].sort_values(by='imdb_score',ascending=False).head(250)
imdb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,profit
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank RedemptionÂ,1689764,13495,Bob Gunton,0.0,escape from prison|first person narration|pris...,http://www.imdb.com/title/tt0111161/?ref_=fn_t...,4144,English,25.0,1994.0,9.3,1.85,108000,3.341469
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The GodfatherÂ,1155770,28122,Robert Duvall,1.0,crime family|mafia|organized crime|patriarch|r...,http://www.imdb.com/title/tt0068646/?ref_=fn_t...,2238,English,6.0,1972.0,9.2,1.85,43000,128.821952
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark KnightÂ,1676169,57802,Morgan Freeman,0.0,based on comic book|dc comics|psychopath|star ...,http://www.imdb.com/title/tt0468569/?ref_=fn_t...,4667,English,185.0,2008.0,9.0,2.35,37000,348.316061
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part IIÂ,790926,39960,Robert Duvall,1.0,1950s|corrupt politician|lake tahoe nevada|mel...,http://www.imdb.com/title/tt0071562/?ref_=fn_t...,650,English,13.0,1974.0,9.0,1.85,14000,44.300000
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the KingÂ,1215718,6434,Bernard Hill,2.0,battle|epic|king|orc|ring,http://www.imdb.com/title/tt0167260/?ref_=fn_t...,3189,English,94.0,2003.0,8.9,2.35,16000,283.019252
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Jon Favreau,486.0,318.298180,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron ManÂ,696338,39252,Jon Favreau,3.0,afghanistan|billionaire|inventor|playboy|u.s. ...,http://www.imdb.com/title/tt0371746/?ref_=fn_t...,1055,English,140.0,2008.0,7.9,2.35,10000,178.298180
75,Doug Liman,585.0,100.189501,Action|Adventure|Sci-Fi,Tom Cruise,Edge of TomorrowÂ,431620,12652,Noah Taylor,1.0,alien|combat|dying repeatedly|end of the world...,http://www.imdb.com/title/tt1631867/?ref_=fn_t...,741,English,178.0,2014.0,7.9,2.35,77000,-77.810499
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-ZaaraÂ,34449,9984,Anupam Kher,0.0,fair|pakistan|prison|rescue|stranded,http://www.imdb.com/title/tt0420332/?ref_=fn_t...,119,Hindi,7.0,2004.0,7.9,2.35,2000,-4.078262
99,Peter Jackson,645.0,303.001229,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected JourneyÂ,637246,9152,James Nesbitt,NaN,dragon|dwarf|hobbit|orc|wizard,http://www.imdb.com/title/tt0903624/?ref_=fn_t...,1367,English,180.0,2012.0,7.9,2.35,166000,123.001229
3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The ChorusÂ,44151,745,GÃ©rard Jugnot,0.0,boarding school|boy|choir|school|teacher,http://www.imdb.com/title/tt0372824/?ref_=fn_t...,110,French,5.5,2004.0,7.9,2.35,0,-1.870242

In [40]:
imdb_Top_250['Rank']= imdb_Top_250['imdb_score'].rank(method='first',ascending=False)
imdb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,...,movie_imdb_link,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,profit,Rank
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank RedemptionÂ,1689764,13495,Bob Gunton,0.0,...,http://www.imdb.com/title/tt0111161/?ref_=fn_t...,4144,English,25.0,1994.0,9.3,1.85,108000,3.341469,1.0
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The GodfatherÂ,1155770,28122,Robert Duvall,1.0,...,http://www.imdb.com/title/tt0068646/?ref_=fn_t...,2238,English,6.0,1972.0,9.2,1.85,43000,128.821952,2.0
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark KnightÂ,1676169,57802,Morgan Freeman,0.0,...,http://www.imdb.com/title/tt0468569/?ref_=fn_t...,4667,English,185.0,2008.0,9.0,2.35,37000,348.316061,3.0
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part IIÂ,790926,39960,Robert Duvall,1.0,...,http://www.imdb.com/title/tt0071562/?ref_=fn_t...,650,English,13.0,1974.0,9.0,1.85,14000,44.300000,4.0
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the KingÂ,1215718,6434,Bernard Hill,2.0,...,http://www.imdb.com/title/tt0167260/?ref_=fn_t...,3189,English,94.0,2003.0,8.9,2.35,16000,283.019252,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Jon Favreau,486.0,318.298180,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron ManÂ,696338,39252,Jon Favreau,3.0,...,http://www.imdb.com/title/tt0371746/?ref_=fn_t...,1055,English,140.0,2008.0,7.9,2.35,10000,178.298180,246.0
75,Doug Liman,585.0,100.189501,Action|Adventure|Sci-Fi,Tom Cruise,Edge of TomorrowÂ,431620,12652,Noah Taylor,1.0,...,http://www.imdb.com/title/tt1631867/?ref_=fn_t...,741,English,178.0,2014.0,7.9,2.35,77000,-77.810499,247.0
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-ZaaraÂ,34449,9984,Anupam Kher,0.0,...,http://www.imdb.com/title/tt0420332/?ref_=fn_t...,119,Hindi,7.0,2004.0,7.9,2.35,2000,-4.078262,248.0
99,Peter Jackson,645.0,303.001229,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected JourneyÂ,637246,9152,James Nesbitt,NaN,...,http://www.imdb.com/title/tt0903624/?ref_=fn_t...,1367,English,180.0,2012.0,7.9,2.35,166000,123.001229,249.0
3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The ChorusÂ,44151,745,GÃ©rard Jugnot,0.0,...,http://www.imdb.com/title/tt0372824/?ref_=fn_t...,110,French,5.5,2004.0,7.9,2.35,0,-1.870242,250.0

In [41]:
imdb_Top_250[imdb_Top_250['language']!='English']
imdb_Top_250

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,...,movie_imdb_link,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,profit,Rank
1937,Frank Darabont,199.0,28.341469,Crime|Drama,Morgan Freeman,The Shawshank RedemptionÂ,1689764,13495,Bob Gunton,0.0,...,http://www.imdb.com/title/tt0111161/?ref_=fn_t...,4144,English,25.0,1994.0,9.3,1.85,108000,3.341469,1.0
3466,Francis Ford Coppola,208.0,134.821952,Crime|Drama,Al Pacino,The GodfatherÂ,1155770,28122,Robert Duvall,1.0,...,http://www.imdb.com/title/tt0068646/?ref_=fn_t...,2238,English,6.0,1972.0,9.2,1.85,43000,128.821952,2.0
66,Christopher Nolan,645.0,533.316061,Action|Crime|Drama|Thriller,Christian Bale,The Dark KnightÂ,1676169,57802,Morgan Freeman,0.0,...,http://www.imdb.com/title/tt0468569/?ref_=fn_t...,4667,English,185.0,2008.0,9.0,2.35,37000,348.316061,3.0
2837,Francis Ford Coppola,149.0,57.300000,Crime|Drama,Robert De Niro,The Godfather: Part IIÂ,790926,39960,Robert Duvall,1.0,...,http://www.imdb.com/title/tt0071562/?ref_=fn_t...,650,English,13.0,1974.0,9.0,1.85,14000,44.300000,4.0
339,Peter Jackson,328.0,377.019252,Action|Adventure|Drama|Fantasy,Orlando Bloom,The Lord of the Rings: The Return of the KingÂ,1215718,6434,Bernard Hill,2.0,...,http://www.imdb.com/title/tt0167260/?ref_=fn_t...,3189,English,94.0,2003.0,8.9,2.35,16000,283.019252,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Jon Favreau,486.0,318.298180,Action|Adventure|Sci-Fi,Robert Downey Jr.,Iron ManÂ,696338,39252,Jon Favreau,3.0,...,http://www.imdb.com/title/tt0371746/?ref_=fn_t...,1055,English,140.0,2008.0,7.9,2.35,10000,178.298180,246.0
75,Doug Liman,585.0,100.189501,Action|Adventure|Sci-Fi,Tom Cruise,Edge of TomorrowÂ,431620,12652,Noah Taylor,1.0,...,http://www.imdb.com/title/tt1631867/?ref_=fn_t...,741,English,178.0,2014.0,7.9,2.35,77000,-77.810499,247.0
3510,Yash Chopra,29.0,2.921738,Drama|Musical|Romance,Shah Rukh Khan,Veer-ZaaraÂ,34449,9984,Anupam Kher,0.0,...,http://www.imdb.com/title/tt0420332/?ref_=fn_t...,119,Hindi,7.0,2004.0,7.9,2.35,2000,-4.078262,248.0
99,Peter Jackson,645.0,303.001229,Adventure|Fantasy,Aidan Turner,The Hobbit: An Unexpected JourneyÂ,637246,9152,James Nesbitt,NaN,...,http://www.imdb.com/title/tt0903624/?ref_=fn_t...,1367,English,180.0,2012.0,7.9,2.35,166000,123.001229,249.0
3677,Christophe Barratier,112.0,3.629758,Drama|Music,Jean-Baptiste Maunier,The ChorusÂ,44151,745,GÃ©rard Jugnot,0.0,...,http://www.imdb.com/title/tt0372824/?ref_=fn_t...,110,French,5.5,2004.0,7.9,2.35,0,-1.870242,250.0

In [42]:
# spot veerzara in the dataframe?
#Group the datafarme using the director_name column
#find out the top 10 directors whom the mean of imdb_score is the highest and store them in a new dataframe top10director.

In [43]:
#extract top 10 directors 
movies.groupby('director_name').imdb_score.mean().sort_values(ascending=False).head(10)

director_name
Charles Chaplin          8.600000
Tony Kaye                8.600000
Alfred Hitchcock         8.500000
Ron Fricke               8.500000
Damien Chazelle          8.500000
Majid Majidi             8.500000
Sergio Leone             8.433333
Christopher Nolan        8.425000
S.S. Rajamouli           8.400000
Marius A. Markevicius    8.400000
Name: imdb_score, dtype: float64

# Find popular generes

In [44]:
#youn might have noticed the generes column inthe  dataframe with all the generes of the moies seperated by apipe(i) by out alll the movies generes the first two are most signinificant for any film 
#extract the first two generes column an d store them in two new columns genere_1 and genere_2 some of the movies might have 
# only one genere in such cases extract the single genere into both the columnsi.e for such movies the genere_2 will be the same as genere_1 
#groupm the dataframe using genere_1 as the primary column and genere_2 as the secondury column
#find out the  5 most popular combo of generes by finding the mean of the gross values using the gross column and store them in a new dataframe name pop genere

In [45]:
movies.genres.str.split('|',expand=True).iloc[:,0:2]

                0          1
0          Action  Adventure
1          Action  Adventure
2          Action  Adventure
3          Action   Thriller
5          Action  Adventure
...           ...        ...
5033        Drama     Sci-Fi
5034     Thriller       None
5035       Action      Crime
5037       Comedy      Drama
5042  Documentary       None

[3857 rows x 2 columns]

In [46]:
Tempgenere = movies.genres.str.split('|',expand=True).iloc[:,0:2]
Tempgenere.columns=['genre_1','genre_2']
Tempgenere.genre_2.fillna(Tempgenere.genre_1,inplace=True)
Tempgenere

          genre_1      genre_2
0          Action    Adventure
1          Action    Adventure
2          Action    Adventure
3          Action     Thriller
5          Action    Adventure
...           ...          ...
5033        Drama       Sci-Fi
5034     Thriller     Thriller
5035       Action        Crime
5037       Comedy        Drama
5042  Documentary  Documentary

[3857 rows x 2 columns]

In [47]:
movies=pd.concat([movies,Tempgenere],axis=1)
movies

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,...,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,profit,genre_1,genre_2
0,James Cameron,723.0,760.505847,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,AvatarÂ,886204,4834,Wes Studi,0.0,...,3054,English,237.0000,2009.0,7.9,1.78,33000,523.505847,Action,Adventure
1,Gore Verbinski,302.0,309.404152,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's EndÂ,471220,48350,Jack Davenport,0.0,...,1238,English,300.0000,2007.0,7.1,2.35,0,9.404152,Action,Adventure
2,Sam Mendes,602.0,200.074175,Action|Adventure|Thriller,Christoph Waltz,SpectreÂ,275868,11700,Stephanie Sigman,1.0,...,994,English,245.0000,2015.0,6.8,2.35,85000,-44.925825,Action,Adventure
3,Christopher Nolan,813.0,448.130642,Action|Thriller,Tom Hardy,The Dark Knight RisesÂ,1144337,106759,Joseph Gordon-Levitt,0.0,...,2701,English,250.0000,2012.0,8.5,2.35,164000,198.130642,Action,Thriller
5,Andrew Stanton,462.0,73.058679,Action|Adventure|Sci-Fi,Daryl Sabara,John CarterÂ,212204,1873,Polly Walker,1.0,...,738,English,263.7000,2012.0,6.6,2.35,24000,-190.641321,Action,Adventure
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5033,Shane Carruth,143.0,0.424760,Drama|Sci-Fi|Thriller,Shane Carruth,PrimerÂ,72639,368,Casey Gooden,0.0,...,371,English,0.0070,2004.0,7.0,1.85,19000,0.417760,Drama,Sci-Fi
5034,Neill Dela Llana,35.0,0.070071,Thriller,Ian Gamazon,CaviteÂ,589,0,Quynn Ton,0.0,...,35,English,0.0070,2005.0,6.3,NaN,74,0.063071,Thriller,Thriller
5035,Robert Rodriguez,56.0,2.040920,Action|Crime|Drama|Romance|Thriller,Carlos Gallardo,El MariachiÂ,52055,147,Consuelo GÃ³mez,0.0,...,130,Spanish,0.0070,1992.0,6.9,1.37,0,2.033920,Action,Crime
5037,Edward Burns,14.0,0.004584,Comedy|Drama,Kerry BishÃ©,NewlywedsÂ,1338,690,Daniella Pineda,1.0,...,14,English,0.0090,2011.0,6.4,NaN,413,-0.004416,Comedy,Drama
5042,Jon Gunn,43.0,0.085222,Documentary,John August,My Date with DrewÂ,4285,163,Jon Gunn,0.0,...,84,English,0.0011,2004.0,6.6,1.85,456,0.084122,Documentary,Documentary

In [48]:
movies.groupby(['genre_1','genre_2']).gross.mean().sort_values(ascending=False).head(5)

genre_1    genre_2
Family     Sci-Fi       434.949459
Adventure  Sci-Fi       228.627758
           Family       118.919540
           Animation    116.998550
Action     Adventure    109.595465
Name: gross, dtype: float64

# Find the critic-Favorite and audience-favorite and audience-favorite actors

In [69]:
#create three new dataframes namely Meryl_streep, Leo_Caprico and Brad_Fitt Which contains the movies in which the actors. 'meryl Streep', 'Leonardo Dicaprio' and 'Brad Pitt' are the lead actors use only the actors1__name
#column for extraction.also, make sure that you use the name 'Meryl streep','Leonardo Dicaprio'and 'Brad pit for' the said extraction
#append the rows of these Dartaframes the store them in the new dataframe named combined 
#Group the combined dataframe using the actor_1_name column
#Find the mean of the num_critic_for_reviews and identify the actors which have the highest mean

In [53]:
#movies.memory_usage()
#movies.empty

In [62]:
Meryl_streep = movies[movies['actor_1_name']=='Meryl Streep']
Leo_caprico = movies[movies['actor_1_name']=='Leonardo dicaprio']
Brad_pitt = movies[movies['actor_1_name']=='Brad pitt']

In [61]:
combined = Meryl_streep.append((Leo_caprico,Brad_pitt))
combined

,director_name,num_critic_for_reviews,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,...,num_user_for_reviews,language,budget,title_year,imdb_score,aspect_ratio,movie_facebook_likes,profit,genre_1,genre_2
410,Nancy Meyers,187.0,112.703470,Comedy|Drama|Romance,Meryl Streep,It's ComplicatedÂ,69860,15226,Zoe Kazan,2.0,...,214,English,85.0,2009.0,6.6,1.85,0,27.703470,Comedy,Drama
1106,Curtis Hanson,42.0,46.815748,Action|Adventure|Crime|Thriller,Meryl Streep,The River WildÂ,32544,12161,William Lucking,1.0,...,69,English,45.0,1994.0,6.3,2.35,0,1.815748,Action,Adventure
1204,Nora Ephron,252.0,94.125426,Biography|Drama|Romance,Meryl Streep,Julie & JuliaÂ,79264,13321,Vanessa Ferlito,2.0,...,277,English,40.0,2009.0,7.0,1.85,13000,54.125426,Biography,Drama
1408,David Frankel,208.0,124.732962,Comedy|Drama|Romance,Meryl Streep,The Devil Wears PradaÂ,286178,23923,Rebecca Mader,0.0,...,631,English,35.0,2006.0,6.8,2.35,0,89.732962,Comedy,Drama
1483,Robert Redford,227.0,14.998070,Drama|Thriller|War,Meryl Streep,Lions for LambsÂ,41170,32875,Andrew Garfield,3.0,...,298,English,35.0,2007.0,6.2,2.35,0,-20.001930,Drama,Thriller
1575,Sydney Pollack,66.0,87.100000,Biography|Drama|Romance,Meryl Streep,Out of AfricaÂ,52339,12518,Michael Kitchen,0.0,...,200,English,31.0,1985.0,7.2,1.85,0,56.100000,Biography,Drama
1618,David Frankel,234.0,63.536011,Comedy|Drama|Romance,Meryl Streep,Hope SpringsÂ,34258,19420,Jean Smart,2.0,...,178,English,30.0,2012.0,6.3,2.35,0,33.536011,Comedy,Drama
1674,Carl Franklin,64.0,23.209440,Drama,Meryl Streep,One True ThingÂ,9283,12785,Tom Everett Scott,3.0,...,112,English,30.0,1998.0,7.0,1.85,592,-6.790560,Drama,Drama
1925,Stephen Daldry,174.0,41.597830,Drama|Romance,Meryl Streep,The HoursÂ,102123,12624,Miranda Richardson,3.0,...,660,English,25.0,2002.0,7.6,1.85,0,16.597830,Drama,Romance
2781,Phyllida Lloyd,331.0,29.959436,Biography|Drama|History,Meryl Streep,The Iron LadyÂ,82327,12894,Olivia Colman,1.0,...,350,English,13.0,2011.0,6.4,2.35,18000,16.959436,Biography,Drama
3135,Robert Altman,211.0,20.338609,Comedy|Drama|Music,Meryl Streep,A Prairie Home CompanionÂ,19655,12946,Lily Tomlin,8.0,...,280,English,10.0,2006.0,6.8,2.35,683,10.338609,Comedy,Drama

In [ ]:
num_critic_for_reviews and num_user_for_review

In [63]:
combined.groupby('actor_1_name').num_critic_for_reviews.mean()

actor_1_name
Meryl Streep    181.454545
Name: num_critic_for_reviews, dtype: float64

In [65]:
combined.num_user_for_reviews = combined.num_user_for_reviews.astype('int')
combined.num_user_for_reviews

410     214
1106     69
1204    277
1408    631
1483    298
1575    200
1618    178
1674    112
1925    660
2781    350
3135    280
Name: num_user_for_reviews, dtype: int32

In [66]:
combined.groupby('actor_1_name').num_user_for_reviews.mean()

actor_1_name
Meryl Streep    297.181818
Name: num_user_for_reviews, dtype: float64

In [67]:
combined.groupby('actor_1_name')[['num_critic_for_reviews','num_user_for_reviews']].mean()

              num_critic_for_reviews  num_user_for_reviews
actor_1_name
Meryl Streep              181.454545            297.181818

In [68]:
# Leonardo has aced both the list